// Code generated by protoc-gen-go. DO NOT EDIT.
// source: webpage.proto

package webpage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WebError struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebError) Reset()         { *m = WebError{} }
func (m *WebError) String() string { return proto.CompactTextString(m) }
func (*WebError) ProtoMessage()    {}
func (*WebError) Descriptor() ([]byte, []int) {
	return fileDescriptor_3969cee06fc11a0e, []int{0}
}

func (m *WebError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebError.Unmarshal(m, b)
}
func (m *WebError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebError.Marshal(b, m, deterministic)
}
func (m *WebError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebError.Merge(m, src)
}
func (m *WebError) XXX_Size() int {
	return xxx_messageInfo_WebError.Size(m)
}
func (m *WebError) XXX_DiscardUnknown() {
	xxx_messageInfo_WebError.DiscardUnknown(m)
}

var xxx_messageInfo_WebError proto.InternalMessageInfo

func (m *WebError) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WebError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// UnixTimeStamp int64
type WebpageRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	SinceDate            int64    `protobuf:"varint,2,opt,name=SinceDate,proto3" json:"SinceDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebpageRequest) Reset()         { *m = WebpageRequest{} }
func (m *WebpageRequest) String() string { return proto.CompactTextString(m) }
func (*WebpageRequest) ProtoMessage()    {}
func (*WebpageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3969cee06fc11a0e, []int{1}
}

func (m *WebpageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebpageRequest.Unmarshal(m, b)
}
func (m *WebpageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebpageRequest.Marshal(b, m, deterministic)
}
func (m *WebpageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebpageRequest.Merge(m, src)
}
func (m *WebpageRequest) XXX_Size() int {
	return xxx_messageInfo_WebpageRequest.Size(m)
}
func (m *WebpageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WebpageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WebpageRequest proto.InternalMessageInfo

func (m *WebpageRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *WebpageRequest) GetSinceDate() int64 {
	if m != nil {
		return m.SinceDate
	}
	return 0
}

type AcmArticle struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ArchiveDate          int64    `protobuf:"varint,2,opt,name=ArchiveDate,proto3" json:"ArchiveDate,omitempty"`
	ArticleNumber        string   `protobuf:"bytes,3,opt,name=ArticleNumber,proto3" json:"ArticleNumber,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	ImageSource          string   `protobuf:"bytes,5,opt,name=ImageSource,proto3" json:"ImageSource,omitempty"`
	JournalName          string   `protobuf:"bytes,6,opt,name=JournalName,proto3" json:"JournalName,omitempty"`
	AuthorName           string   `protobuf:"bytes,7,opt,name=AuthorName,proto3" json:"AuthorName,omitempty"`
	JournalDate          int64    `protobuf:"varint,8,opt,name=JournalDate,proto3" json:"JournalDate,omitempty"`
	WebReference         string   `protobuf:"bytes,9,opt,name=WebReference,proto3" json:"WebReference,omitempty"`
	Summary              string   `protobuf:"bytes,10,opt,name=Summary,proto3" json:"Summary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcmArticle) Reset()         { *m = AcmArticle{} }
func (m *AcmArticle) String() string { return proto.CompactTextString(m) }
func (*AcmArticle) ProtoMessage()    {}
func (*AcmArticle) Descriptor() ([]byte, []int) {
	return fileDescriptor_3969cee06fc11a0e, []int{2}
}

func (m *AcmArticle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcmArticle.Unmarshal(m, b)
}
func (m *AcmArticle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcmArticle.Marshal(b, m, deterministic)
}
func (m *AcmArticle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcmArticle.Merge(m, src)
}
func (m *AcmArticle) XXX_Size() int {
	return xxx_messageInfo_AcmArticle.Size(m)
}
func (m *AcmArticle) XXX_DiscardUnknown() {
	xxx_messageInfo_AcmArticle.DiscardUnknown(m)
}

var xxx_messageInfo_AcmArticle proto.InternalMessageInfo

func (m *AcmArticle) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AcmArticle) GetArchiveDate() int64 {
	if m != nil {
		return m.ArchiveDate
	}
	return 0
}

func (m *AcmArticle) GetArticleNumber() string {
	if m != nil {
		return m.ArticleNumber
	}
	return ""
}

func (m *AcmArticle) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AcmArticle) GetImageSource() string {
	if m != nil {
		return m.ImageSource
	}
	return ""
}

func (m *AcmArticle) GetJournalName() string {
	if m != nil {
		return m.JournalName
	}
	return ""
}

func (m *AcmArticle) GetAuthorName() string {
	if m != nil {
		return m.AuthorName
	}
	return ""
}

func (m *AcmArticle) GetJournalDate() int64 {
	if m != nil {
		return m.JournalDate
	}
	return 0
}

func (m *AcmArticle) GetWebReference() string {
	if m != nil {
		return m.WebReference
	}
	return ""
}

func (m *AcmArticle) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

type WebpageResponse struct {
	Topic                string        `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Werror               *WebError     `protobuf:"bytes,2,opt,name=Werror,proto3" json:"Werror,omitempty"`
	AcmArticleList       []*AcmArticle `protobuf:"bytes,3,rep,name=AcmArticleList,proto3" json:"AcmArticleList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *WebpageResponse) Reset()         { *m = WebpageResponse{} }
func (m *WebpageResponse) String() string { return proto.CompactTextString(m) }
func (*WebpageResponse) ProtoMessage()    {}
func (*WebpageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3969cee06fc11a0e, []int{3}
}

func (m *WebpageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebpageResponse.Unmarshal(m, b)
}
func (m *WebpageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebpageResponse.Marshal(b, m, deterministic)
}
func (m *WebpageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebpageResponse.Merge(m, src)
}
func (m *WebpageResponse) XXX_Size() int {
	return xxx_messageInfo_WebpageResponse.Size(m)
}
func (m *WebpageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WebpageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WebpageResponse proto.InternalMessageInfo

func (m *WebpageResponse) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *WebpageResponse) GetWerror() *WebError {
	if m != nil {
		return m.Werror
	}
	return nil
}

func (m *WebpageResponse) GetAcmArticleList() []*AcmArticle {
	if m != nil {
		return m.AcmArticleList
	}
	return nil
}

func init() {
	proto.RegisterType((*WebError)(nil), "WebError")
	proto.RegisterType((*WebpageRequest)(nil), "WebpageRequest")
	proto.RegisterType((*AcmArticle)(nil), "AcmArticle")
	proto.RegisterType((*WebpageResponse)(nil), "WebpageResponse")
}

func init() { proto.RegisterFile("webpage.proto", fileDescriptor_3969cee06fc11a0e) }

var fileDescriptor_3969cee06fc11a0e = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x6f, 0xb2, 0x40,
	0x10, 0xc6, 0x5f, 0xc1, 0x7f, 0x0c, 0xaf, 0xda, 0x6c, 0x7a, 0xd8, 0x34, 0x4d, 0x43, 0x49, 0x0f,
	0x9e, 0x48, 0xaa, 0x97, 0x5e, 0x89, 0xf6, 0x60, 0xd3, 0x7a, 0x58, 0x9a, 0x70, 0x86, 0x75, 0xaa,
	0x24, 0xc2, 0xd2, 0x05, 0x34, 0x3d, 0xf5, 0x9b, 0xf5, 0xb3, 0x35, 0x2c, 0xa8, 0x68, 0xd2, 0x1b,
	0xf3, 0xdb, 0x67, 0x1e, 0x66, 0xf7, 0x19, 0x18, 0xec, 0x31, 0x4c, 0x83, 0x35, 0x3a, 0xa9, 0x14,
	0xb9, 0xb0, 0x9f, 0xa0, 0xef, 0x63, 0xf8, 0x2c, 0xa5, 0x90, 0x84, 0x40, 0x7b, 0x26, 0x56, 0x48,
	0x5b, 0x56, 0x6b, 0xdc, 0x61, 0xea, 0x9b, 0x50, 0xe8, 0xbd, 0x61, 0x96, 0x05, 0x6b, 0xa4, 0x9a,
	0xd5, 0x1a, 0x1b, 0xec, 0x50, 0xda, 0x73, 0x18, 0xfa, 0x95, 0x15, 0xc3, 0xcf, 0x02, 0xb3, 0x9c,
	0x5c, 0x43, 0xe7, 0x5d, 0xa4, 0x11, 0x57, 0x06, 0x06, 0xab, 0x0a, 0x72, 0x0b, 0x86, 0x17, 0x25,
	0x1c, 0xe7, 0x41, 0x5e, 0x79, 0xe8, 0xec, 0x04, 0xec, 0x1f, 0x0d, 0xc0, 0xe5, 0xb1, 0x2b, 0xf3,
	0x88, 0x6f, 0x91, 0x0c, 0x41, 0x5b, 0xac, 0x54, 0xff, 0x80, 0x69, 0x8b, 0x15, 0xb1, 0xc0, 0x74,
	0x25, 0xdf, 0x44, 0xbb, 0x66, 0x7b, 0x13, 0x91, 0x07, 0x18, 0xd4, 0xcd, 0xcb, 0x22, 0x0e, 0x51,
	0x52, 0x5d, 0xfd, 0xfc, 0x1c, 0xaa, 0xd1, 0xa2, 0x7c, 0x8b, 0xb4, 0x5d, 0x8f, 0x56, 0x16, 0xa5,
	0xfb, 0x22, 0x0e, 0xd6, 0xe8, 0x89, 0x42, 0x72, 0xa4, 0x1d, 0x75, 0xd6, 0x44, 0xa5, 0xe2, 0x45,
	0x14, 0x32, 0x09, 0xb6, 0xcb, 0x20, 0x46, 0xda, 0xad, 0x14, 0x0d, 0x44, 0xee, 0x00, 0xdc, 0x22,
	0xdf, 0x08, 0xa9, 0x04, 0x3d, 0x25, 0x68, 0x90, 0x86, 0x83, 0xba, 0x41, 0xbf, 0xba, 0x41, 0x03,
	0x11, 0x1b, 0xfe, 0xfb, 0x18, 0x32, 0xfc, 0x40, 0x89, 0x09, 0x47, 0x6a, 0x28, 0x8f, 0x33, 0x56,
	0xc6, 0xe0, 0x15, 0x71, 0x1c, 0xc8, 0x2f, 0x0a, 0x55, 0x0c, 0x75, 0x69, 0x7f, 0xc3, 0xe8, 0x18,
	0x43, 0x96, 0x8a, 0x24, 0xc3, 0x3f, 0x72, 0xb8, 0x87, 0xae, 0x8f, 0x65, 0xce, 0xea, 0x15, 0xcd,
	0x89, 0xe1, 0x1c, 0x82, 0x67, 0xf5, 0x01, 0x99, 0xc2, 0xf0, 0x94, 0xc5, 0x6b, 0x94, 0xe5, 0x54,
	0xb7, 0xf4, 0xb1, 0x39, 0x31, 0x9d, 0x13, 0x66, 0x17, 0x92, 0xc9, 0xec, 0xb8, 0x07, 0x1e, 0xca,
	0x5d, 0xc4, 0x91, 0x3c, 0x02, 0x2c, 0x71, 0x5f, 0x43, 0x32, 0x72, 0xce, 0xd7, 0xe4, 0xe6, 0xca,
	0xb9, 0x18, 0xd8, 0xfe, 0x17, 0x76, 0xd5, 0x36, 0x4e, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x69,
	0x48, 0x20, 0x0f, 0x9e, 0x02, 0x00, 0x00,
}
