echo "Case-sensitive search!"
grep -l $1 ./article/article.go
grep -l $1 ./article/article.pb.micro.go
grep -l $1 ./article/article.pb.go
grep -l $1 ./article/article.micro.go
grep -l $1 ./conditional/conditional.go
grep -l $1 ./conditional/condprob.pb.go
grep -l $1 ./conditional/condprob.pb.go
grep -l $1 ./conditional/condprob.pb.micro.go
grep -l $1 ./database/database.go
grep -l $1 ./filesystem/filesystem.go
grep -l $1 ./headers/headers.go
grep -l $1 ./nulltime/nulltime.go
grep -l $1 ./nulltime/nulltime_test.go
grep -l $1 ./timeevent/timeevent.pb.go
grep -l $1 ./timeevent/timeevent.micro.go
grep -l $1 ./timeevent/timeevent.pb.micro.go
grep -l $1 ./timestampinterval/timestampinterval.go
grep -l $1 ./timestampinterval/timestampinterval.pb.go
grep -l $1 ./timestampinterval/timestampinterval.pb.micro.go
grep -l $1 ./timestampinterval/timestampinterval.micro.go
grep -l $1 ./vocabulary/vocabulary.go
grep -l $1 ./webpage/webpage.pb.go
grep -l $1 ./webpage/webpage.micro.go
grep -l $1 ./webpage/webpage.pb.micro.go
grep -l $1 ./wordscore/wordscore.pb.go
grep -l $1 ./wordscore/wordscore.micro.go
grep -l $1 ./wordscore/wordscore.pb.micro.go
