// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: condprob.proto

package wordscore

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ConditionalProbabilityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WordA string `protobuf:"bytes,1,opt,name=WordA,proto3" json:"WordA,omitempty"`
	WordB string `protobuf:"bytes,2,opt,name=WordB,proto3" json:"WordB,omitempty"`
}

func (x *ConditionalProbabilityRequest) Reset() {
	*x = ConditionalProbabilityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_condprob_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConditionalProbabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionalProbabilityRequest) ProtoMessage() {}

func (x *ConditionalProbabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_condprob_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionalProbabilityRequest.ProtoReflect.Descriptor instead.
func (*ConditionalProbabilityRequest) Descriptor() ([]byte, []int) {
	return file_condprob_proto_rawDescGZIP(), []int{0}
}

func (x *ConditionalProbabilityRequest) GetWordA() string {
	if x != nil {
		return x.WordA
	}
	return ""
}

func (x *ConditionalProbabilityRequest) GetWordB() string {
	if x != nil {
		return x.WordB
	}
	return ""
}

type ConditionalProbabilityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConditionalProbability float32 `protobuf:"fixed32,3,opt,name=ConditionalProbability,proto3" json:"ConditionalProbability,omitempty"`
}

func (x *ConditionalProbabilityResponse) Reset() {
	*x = ConditionalProbabilityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_condprob_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConditionalProbabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionalProbabilityResponse) ProtoMessage() {}

func (x *ConditionalProbabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_condprob_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionalProbabilityResponse.ProtoReflect.Descriptor instead.
func (*ConditionalProbabilityResponse) Descriptor() ([]byte, []int) {
	return file_condprob_proto_rawDescGZIP(), []int{1}
}

func (x *ConditionalProbabilityResponse) GetConditionalProbability() float32 {
	if x != nil {
		return x.ConditionalProbability
	}
	return 0
}

var File_condprob_proto protoreflect.FileDescriptor

var file_condprob_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x4b, 0x0a, 0x1d, 0x43,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x57, 0x6f, 0x72, 0x64, 0x41, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x57, 0x6f, 0x72,
	0x64, 0x41, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x6f, 0x72, 0x64, 0x42, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x57, 0x6f, 0x72, 0x64, 0x42, 0x22, 0x58, 0x0a, 0x1e, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x16, 0x43, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x16, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x32, 0x8d, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x73, 0x0a,
	0x1a, 0x43, 0x61, 0x6c, 0x63, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x28, 0x2e, 0x77, 0x6f,
	0x72, 0x64, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x6f,
	0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_condprob_proto_rawDescOnce sync.Once
	file_condprob_proto_rawDescData = file_condprob_proto_rawDesc
)

func file_condprob_proto_rawDescGZIP() []byte {
	file_condprob_proto_rawDescOnce.Do(func() {
		file_condprob_proto_rawDescData = protoimpl.X.CompressGZIP(file_condprob_proto_rawDescData)
	})
	return file_condprob_proto_rawDescData
}

var file_condprob_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_condprob_proto_goTypes = []interface{}{
	(*ConditionalProbabilityRequest)(nil),  // 0: wordscore.ConditionalProbabilityRequest
	(*ConditionalProbabilityResponse)(nil), // 1: wordscore.ConditionalProbabilityResponse
}
var file_condprob_proto_depIdxs = []int32{
	0, // 0: wordscore.ConditionalProbability.CalcConditionalProbability:input_type -> wordscore.ConditionalProbabilityRequest
	1, // 1: wordscore.ConditionalProbability.CalcConditionalProbability:output_type -> wordscore.ConditionalProbabilityResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_condprob_proto_init() }
func file_condprob_proto_init() {
	if File_condprob_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_condprob_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConditionalProbabilityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_condprob_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConditionalProbabilityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_condprob_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_condprob_proto_goTypes,
		DependencyIndexes: file_condprob_proto_depIdxs,
		MessageInfos:      file_condprob_proto_msgTypes,
	}.Build()
	File_condprob_proto = out.File
	file_condprob_proto_rawDesc = nil
	file_condprob_proto_goTypes = nil
	file_condprob_proto_depIdxs = nil
}
