// Code generated by protoc-gen-go. DO NOT EDIT.
// source: timestampinterval.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MTimeStampInterval_MTimeFrameType int32

const (
	MTimeStampInterval_TFUnknown MTimeStampInterval_MTimeFrameType = 0
	MTimeStampInterval_TFWeek    MTimeStampInterval_MTimeFrameType = 1
	MTimeStampInterval_TFMonth   MTimeStampInterval_MTimeFrameType = 2
	MTimeStampInterval_TFQuarter MTimeStampInterval_MTimeFrameType = 3
	MTimeStampInterval_TFYear    MTimeStampInterval_MTimeFrameType = 4
	MTimeStampInterval_TFSpan    MTimeStampInterval_MTimeFrameType = 5
)

var MTimeStampInterval_MTimeFrameType_name = map[int32]string{
	0: "TFUnknown",
	1: "TFWeek",
	2: "TFMonth",
	3: "TFQuarter",
	4: "TFYear",
	5: "TFSpan",
}

var MTimeStampInterval_MTimeFrameType_value = map[string]int32{
	"TFUnknown": 0,
	"TFWeek":    1,
	"TFMonth":   2,
	"TFQuarter": 3,
	"TFYear":    4,
	"TFSpan":    5,
}

func (x MTimeStampInterval_MTimeFrameType) String() string {
	return proto.EnumName(MTimeStampInterval_MTimeFrameType_name, int32(x))
}

func (MTimeStampInterval_MTimeFrameType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f2c9cae6b54ed7e3, []int{1, 0}
}

type Error struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c9cae6b54ed7e3, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MTimeStampInterval struct {
	Timeframetype        MTimeStampInterval_MTimeFrameType `protobuf:"varint,1,opt,name=Timeframetype,proto3,enum=pb.MTimeStampInterval_MTimeFrameType" json:"Timeframetype,omitempty"`
	StartTime            *timestamp.Timestamp              `protobuf:"bytes,2,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              *timestamp.Timestamp              `protobuf:"bytes,3,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *MTimeStampInterval) Reset()         { *m = MTimeStampInterval{} }
func (m *MTimeStampInterval) String() string { return proto.CompactTextString(m) }
func (*MTimeStampInterval) ProtoMessage()    {}
func (*MTimeStampInterval) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c9cae6b54ed7e3, []int{1}
}

func (m *MTimeStampInterval) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MTimeStampInterval.Unmarshal(m, b)
}
func (m *MTimeStampInterval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MTimeStampInterval.Marshal(b, m, deterministic)
}
func (m *MTimeStampInterval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MTimeStampInterval.Merge(m, src)
}
func (m *MTimeStampInterval) XXX_Size() int {
	return xxx_messageInfo_MTimeStampInterval.Size(m)
}
func (m *MTimeStampInterval) XXX_DiscardUnknown() {
	xxx_messageInfo_MTimeStampInterval.DiscardUnknown(m)
}

var xxx_messageInfo_MTimeStampInterval proto.InternalMessageInfo

func (m *MTimeStampInterval) GetTimeframetype() MTimeStampInterval_MTimeFrameType {
	if m != nil {
		return m.Timeframetype
	}
	return MTimeStampInterval_TFUnknown
}

func (m *MTimeStampInterval) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *MTimeStampInterval) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

type TimeEventRequest struct {
	Topic                string              `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Timestampinterval    *MTimeStampInterval `protobuf:"bytes,2,opt,name=Timestampinterval,proto3" json:"Timestampinterval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TimeEventRequest) Reset()         { *m = TimeEventRequest{} }
func (m *TimeEventRequest) String() string { return proto.CompactTextString(m) }
func (*TimeEventRequest) ProtoMessage()    {}
func (*TimeEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c9cae6b54ed7e3, []int{2}
}

func (m *TimeEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeEventRequest.Unmarshal(m, b)
}
func (m *TimeEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeEventRequest.Marshal(b, m, deterministic)
}
func (m *TimeEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeEventRequest.Merge(m, src)
}
func (m *TimeEventRequest) XXX_Size() int {
	return xxx_messageInfo_TimeEventRequest.Size(m)
}
func (m *TimeEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TimeEventRequest proto.InternalMessageInfo

func (m *TimeEventRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *TimeEventRequest) GetTimestampinterval() *MTimeStampInterval {
	if m != nil {
		return m.Timestampinterval
	}
	return nil
}

type TimeEventResponse struct {
	Completed            bool     `protobuf:"varint,1,opt,name=Completed,proto3" json:"Completed,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeEventResponse) Reset()         { *m = TimeEventResponse{} }
func (m *TimeEventResponse) String() string { return proto.CompactTextString(m) }
func (*TimeEventResponse) ProtoMessage()    {}
func (*TimeEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c9cae6b54ed7e3, []int{3}
}

func (m *TimeEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeEventResponse.Unmarshal(m, b)
}
func (m *TimeEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeEventResponse.Marshal(b, m, deterministic)
}
func (m *TimeEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeEventResponse.Merge(m, src)
}
func (m *TimeEventResponse) XXX_Size() int {
	return xxx_messageInfo_TimeEventResponse.Size(m)
}
func (m *TimeEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TimeEventResponse proto.InternalMessageInfo

func (m *TimeEventResponse) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *TimeEventResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.MTimeStampInterval_MTimeFrameType", MTimeStampInterval_MTimeFrameType_name, MTimeStampInterval_MTimeFrameType_value)
	proto.RegisterType((*Error)(nil), "pb.Error")
	proto.RegisterType((*MTimeStampInterval)(nil), "pb.MTimeStampInterval")
	proto.RegisterType((*TimeEventRequest)(nil), "pb.TimeEventRequest")
	proto.RegisterType((*TimeEventResponse)(nil), "pb.TimeEventResponse")
}

func init() { proto.RegisterFile("timestampinterval.proto", fileDescriptor_f2c9cae6b54ed7e3) }

var fileDescriptor_f2c9cae6b54ed7e3 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x51, 0x6b, 0xdb, 0x30,
	0x14, 0x85, 0x17, 0x27, 0x4e, 0xe6, 0x1b, 0x12, 0x3c, 0x31, 0xb6, 0x10, 0x06, 0x19, 0x86, 0xc1,
	0x9e, 0x1c, 0xc8, 0x36, 0xd8, 0xfb, 0x16, 0x43, 0x29, 0x79, 0xa8, 0xa2, 0x52, 0xfa, 0x54, 0xe4,
	0xe4, 0x26, 0x35, 0x89, 0x25, 0x55, 0x56, 0x52, 0xf2, 0xb7, 0xfa, 0x0b, 0x8b, 0x25, 0xbb, 0x21,
	0x4d, 0xa1, 0x6f, 0xd2, 0xe1, 0xbb, 0xe7, 0xf8, 0x1e, 0x0b, 0xbe, 0x9a, 0x2c, 0xc7, 0xc2, 0xf0,
	0x5c, 0x65, 0xc2, 0xa0, 0xde, 0xf3, 0x6d, 0xac, 0xb4, 0x34, 0x92, 0x78, 0x2a, 0x1d, 0x8e, 0xd6,
	0x52, 0xae, 0xb7, 0x38, 0xb6, 0x4a, 0xba, 0x5b, 0x8d, 0x5f, 0x60, 0x07, 0x45, 0x7f, 0xc0, 0x9f,
	0x6a, 0x2d, 0x35, 0x21, 0xd0, 0x5a, 0xc8, 0x25, 0x0e, 0x1a, 0xdf, 0x1b, 0x3f, 0x03, 0x6a, 0xcf,
	0x64, 0x00, 0x9d, 0x1c, 0x8b, 0x82, 0xaf, 0x71, 0xe0, 0x59, 0xb9, 0xbe, 0x46, 0x4f, 0x1e, 0x90,
	0x19, 0xcb, 0x72, 0x9c, 0x97, 0x5e, 0x17, 0x55, 0x30, 0xb9, 0x84, 0x5e, 0x29, 0xae, 0x34, 0xcf,
	0xd1, 0x1c, 0x94, 0x73, 0xeb, 0x4f, 0x7e, 0xc4, 0x2a, 0x8d, 0xcf, 0x71, 0x27, 0x25, 0x25, 0xcc,
	0x0e, 0x0a, 0xe9, 0xe9, 0x2c, 0xf9, 0x0b, 0xc1, 0xdc, 0x70, 0x6d, 0x4a, 0xd5, 0xe6, 0x77, 0x27,
	0xc3, 0xd8, 0xed, 0x13, 0xd7, 0xfb, 0xc4, 0xac, 0xde, 0x87, 0x1e, 0x61, 0xf2, 0x1b, 0x3a, 0x53,
	0xb1, 0xb4, 0x73, 0xcd, 0x77, 0xe7, 0x6a, 0x34, 0xba, 0x83, 0xfe, 0xe9, 0x07, 0x91, 0x1e, 0x04,
	0x2c, 0xb9, 0x16, 0x1b, 0x21, 0x1f, 0x45, 0xf8, 0x81, 0x00, 0xb4, 0x59, 0x72, 0x83, 0xb8, 0x09,
	0x1b, 0xa4, 0x0b, 0x1d, 0x96, 0xcc, 0xa4, 0x30, 0xf7, 0xa1, 0xe7, 0xb8, 0xab, 0x1d, 0xd7, 0x06,
	0x75, 0xd8, 0x74, 0xdc, 0x2d, 0x72, 0x1d, 0xb6, 0xdc, 0x79, 0xae, 0xb8, 0x08, 0xfd, 0x48, 0x40,
	0x58, 0xfa, 0x4f, 0xf7, 0x28, 0x0c, 0xc5, 0x87, 0x1d, 0x16, 0x86, 0x7c, 0x06, 0x9f, 0x49, 0x95,
	0x2d, 0xaa, 0xde, 0xdd, 0x85, 0xfc, 0x87, 0x4f, 0xec, 0xf5, 0x5f, 0xad, 0x2a, 0xf8, 0xf2, 0x76,
	0x97, 0xf4, 0x7c, 0x20, 0xa2, 0xce, 0xa5, 0xca, 0x2b, 0x94, 0x14, 0x05, 0x92, 0x6f, 0x10, 0xfc,
	0x93, 0xb9, 0xda, 0xa2, 0xc1, 0xa5, 0x0d, 0xfd, 0x48, 0x8f, 0x02, 0x19, 0x81, 0x8f, 0xe5, 0x73,
	0xa8, 0xc2, 0x82, 0x32, 0xcc, 0xbe, 0x0f, 0xea, 0xf4, 0xb4, 0x6d, 0x1b, 0xfc, 0xf5, 0x1c, 0x00,
	0x00, 0xff, 0xff, 0x2d, 0x98, 0x68, 0x7e, 0x76, 0x02, 0x00, 0x00,
}
