// Code generated by protoc-gen-go. DO NOT EDIT.
// source: timeevent.proto

package timeevent

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MTimeStampInterval_MTimeFrameType int32

const (
	MTimeStampInterval_TFUnknown MTimeStampInterval_MTimeFrameType = 0
	MTimeStampInterval_TFWeek    MTimeStampInterval_MTimeFrameType = 1
	MTimeStampInterval_TFMonth   MTimeStampInterval_MTimeFrameType = 2
	MTimeStampInterval_TFQuarter MTimeStampInterval_MTimeFrameType = 3
	MTimeStampInterval_TFYear    MTimeStampInterval_MTimeFrameType = 4
	MTimeStampInterval_TFSpan    MTimeStampInterval_MTimeFrameType = 5
)

var MTimeStampInterval_MTimeFrameType_name = map[int32]string{
	0: "TFUnknown",
	1: "TFWeek",
	2: "TFMonth",
	3: "TFQuarter",
	4: "TFYear",
	5: "TFSpan",
}

var MTimeStampInterval_MTimeFrameType_value = map[string]int32{
	"TFUnknown": 0,
	"TFWeek":    1,
	"TFMonth":   2,
	"TFQuarter": 3,
	"TFYear":    4,
	"TFSpan":    5,
}

func (x MTimeStampInterval_MTimeFrameType) String() string {
	return proto.EnumName(MTimeStampInterval_MTimeFrameType_name, int32(x))
}

func (MTimeStampInterval_MTimeFrameType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_04eedac3640e5bc0, []int{1, 0}
}

type GetTimeEventRequest_MEventType int32

const (
	GetTimeEventRequest_ETInProcess GetTimeEventRequest_MEventType = 0
	GetTimeEventRequest_ETFailed    GetTimeEventRequest_MEventType = 1
	GetTimeEventRequest_ETSucceeded GetTimeEventRequest_MEventType = 2
)

var GetTimeEventRequest_MEventType_name = map[int32]string{
	0: "ETInProcess",
	1: "ETFailed",
	2: "ETSucceeded",
}

var GetTimeEventRequest_MEventType_value = map[string]int32{
	"ETInProcess": 0,
	"ETFailed":    1,
	"ETSucceeded": 2,
}

func (x GetTimeEventRequest_MEventType) String() string {
	return proto.EnumName(GetTimeEventRequest_MEventType_name, int32(x))
}

func (GetTimeEventRequest_MEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_04eedac3640e5bc0, []int{4, 0}
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_04eedac3640e5bc0, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MTimeStampInterval struct {
	Timeframetype        MTimeStampInterval_MTimeFrameType `protobuf:"varint,1,opt,name=Timeframetype,proto3,enum=MTimeStampInterval_MTimeFrameType" json:"Timeframetype,omitempty"`
	StartTime            int64                             `protobuf:"varint,2,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              int64                             `protobuf:"varint,3,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *MTimeStampInterval) Reset()         { *m = MTimeStampInterval{} }
func (m *MTimeStampInterval) String() string { return proto.CompactTextString(m) }
func (*MTimeStampInterval) ProtoMessage()    {}
func (*MTimeStampInterval) Descriptor() ([]byte, []int) {
	return fileDescriptor_04eedac3640e5bc0, []int{1}
}

func (m *MTimeStampInterval) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MTimeStampInterval.Unmarshal(m, b)
}
func (m *MTimeStampInterval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MTimeStampInterval.Marshal(b, m, deterministic)
}
func (m *MTimeStampInterval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MTimeStampInterval.Merge(m, src)
}
func (m *MTimeStampInterval) XXX_Size() int {
	return xxx_messageInfo_MTimeStampInterval.Size(m)
}
func (m *MTimeStampInterval) XXX_DiscardUnknown() {
	xxx_messageInfo_MTimeStampInterval.DiscardUnknown(m)
}

var xxx_messageInfo_MTimeStampInterval proto.InternalMessageInfo

func (m *MTimeStampInterval) GetTimeframetype() MTimeStampInterval_MTimeFrameType {
	if m != nil {
		return m.Timeframetype
	}
	return MTimeStampInterval_TFUnknown
}

func (m *MTimeStampInterval) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *MTimeStampInterval) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type TimeEventRequest struct {
	Topic                string              `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	EventId              int32               `protobuf:"varint,2,opt,name=EventId,proto3" json:"EventId,omitempty"`
	Timestampinterval    *MTimeStampInterval `protobuf:"bytes,3,opt,name=Timestampinterval,proto3" json:"Timestampinterval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TimeEventRequest) Reset()         { *m = TimeEventRequest{} }
func (m *TimeEventRequest) String() string { return proto.CompactTextString(m) }
func (*TimeEventRequest) ProtoMessage()    {}
func (*TimeEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04eedac3640e5bc0, []int{2}
}

func (m *TimeEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeEventRequest.Unmarshal(m, b)
}
func (m *TimeEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeEventRequest.Marshal(b, m, deterministic)
}
func (m *TimeEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeEventRequest.Merge(m, src)
}
func (m *TimeEventRequest) XXX_Size() int {
	return xxx_messageInfo_TimeEventRequest.Size(m)
}
func (m *TimeEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TimeEventRequest proto.InternalMessageInfo

func (m *TimeEventRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *TimeEventRequest) GetEventId() int32 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *TimeEventRequest) GetTimestampinterval() *MTimeStampInterval {
	if m != nil {
		return m.Timestampinterval
	}
	return nil
}

type TimeEventResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeEventResponse) Reset()         { *m = TimeEventResponse{} }
func (m *TimeEventResponse) String() string { return proto.CompactTextString(m) }
func (*TimeEventResponse) ProtoMessage()    {}
func (*TimeEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04eedac3640e5bc0, []int{3}
}

func (m *TimeEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeEventResponse.Unmarshal(m, b)
}
func (m *TimeEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeEventResponse.Marshal(b, m, deterministic)
}
func (m *TimeEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeEventResponse.Merge(m, src)
}
func (m *TimeEventResponse) XXX_Size() int {
	return xxx_messageInfo_TimeEventResponse.Size(m)
}
func (m *TimeEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TimeEventResponse proto.InternalMessageInfo

func (m *TimeEventResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetTimeEventRequest struct {
	Topic                string                         `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	EventType            GetTimeEventRequest_MEventType `protobuf:"varint,2,opt,name=EventType,proto3,enum=GetTimeEventRequest_MEventType" json:"EventType,omitempty"`
	Timestampinterval    *MTimeStampInterval            `protobuf:"bytes,3,opt,name=Timestampinterval,proto3" json:"Timestampinterval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GetTimeEventRequest) Reset()         { *m = GetTimeEventRequest{} }
func (m *GetTimeEventRequest) String() string { return proto.CompactTextString(m) }
func (*GetTimeEventRequest) ProtoMessage()    {}
func (*GetTimeEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04eedac3640e5bc0, []int{4}
}

func (m *GetTimeEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTimeEventRequest.Unmarshal(m, b)
}
func (m *GetTimeEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTimeEventRequest.Marshal(b, m, deterministic)
}
func (m *GetTimeEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTimeEventRequest.Merge(m, src)
}
func (m *GetTimeEventRequest) XXX_Size() int {
	return xxx_messageInfo_GetTimeEventRequest.Size(m)
}
func (m *GetTimeEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTimeEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTimeEventRequest proto.InternalMessageInfo

func (m *GetTimeEventRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *GetTimeEventRequest) GetEventType() GetTimeEventRequest_MEventType {
	if m != nil {
		return m.EventType
	}
	return GetTimeEventRequest_ETInProcess
}

func (m *GetTimeEventRequest) GetTimestampinterval() *MTimeStampInterval {
	if m != nil {
		return m.Timestampinterval
	}
	return nil
}

type SystemEvent struct {
	Id                   uint32              `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Topic                string              `protobuf:"bytes,2,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Success              bool                `protobuf:"varint,3,opt,name=Success,proto3" json:"Success,omitempty"`
	Timestampinterval    *MTimeStampInterval `protobuf:"bytes,4,opt,name=Timestampinterval,proto3" json:"Timestampinterval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SystemEvent) Reset()         { *m = SystemEvent{} }
func (m *SystemEvent) String() string { return proto.CompactTextString(m) }
func (*SystemEvent) ProtoMessage()    {}
func (*SystemEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_04eedac3640e5bc0, []int{5}
}

func (m *SystemEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemEvent.Unmarshal(m, b)
}
func (m *SystemEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemEvent.Marshal(b, m, deterministic)
}
func (m *SystemEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemEvent.Merge(m, src)
}
func (m *SystemEvent) XXX_Size() int {
	return xxx_messageInfo_SystemEvent.Size(m)
}
func (m *SystemEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemEvent.DiscardUnknown(m)
}

var xxx_messageInfo_SystemEvent proto.InternalMessageInfo

func (m *SystemEvent) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SystemEvent) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SystemEvent) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SystemEvent) GetTimestampinterval() *MTimeStampInterval {
	if m != nil {
		return m.Timestampinterval
	}
	return nil
}

type GetTimeEventResponse struct {
	SystemEventList      []*SystemEvent `protobuf:"bytes,1,rep,name=SystemEventList,proto3" json:"SystemEventList,omitempty"`
	Error                *Error         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetTimeEventResponse) Reset()         { *m = GetTimeEventResponse{} }
func (m *GetTimeEventResponse) String() string { return proto.CompactTextString(m) }
func (*GetTimeEventResponse) ProtoMessage()    {}
func (*GetTimeEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04eedac3640e5bc0, []int{6}
}

func (m *GetTimeEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTimeEventResponse.Unmarshal(m, b)
}
func (m *GetTimeEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTimeEventResponse.Marshal(b, m, deterministic)
}
func (m *GetTimeEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTimeEventResponse.Merge(m, src)
}
func (m *GetTimeEventResponse) XXX_Size() int {
	return xxx_messageInfo_GetTimeEventResponse.Size(m)
}
func (m *GetTimeEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTimeEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTimeEventResponse proto.InternalMessageInfo

func (m *GetTimeEventResponse) GetSystemEventList() []*SystemEvent {
	if m != nil {
		return m.SystemEventList
	}
	return nil
}

func (m *GetTimeEventResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterEnum("MTimeStampInterval_MTimeFrameType", MTimeStampInterval_MTimeFrameType_name, MTimeStampInterval_MTimeFrameType_value)
	proto.RegisterEnum("GetTimeEventRequest_MEventType", GetTimeEventRequest_MEventType_name, GetTimeEventRequest_MEventType_value)
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterType((*MTimeStampInterval)(nil), "MTimeStampInterval")
	proto.RegisterType((*TimeEventRequest)(nil), "TimeEventRequest")
	proto.RegisterType((*TimeEventResponse)(nil), "TimeEventResponse")
	proto.RegisterType((*GetTimeEventRequest)(nil), "GetTimeEventRequest")
	proto.RegisterType((*SystemEvent)(nil), "SystemEvent")
	proto.RegisterType((*GetTimeEventResponse)(nil), "GetTimeEventResponse")
}

func init() { proto.RegisterFile("timeevent.proto", fileDescriptor_04eedac3640e5bc0) }

var fileDescriptor_04eedac3640e5bc0 = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x8e, 0x9d, 0x3a, 0xad, 0xc7, 0x4d, 0xe2, 0x6e, 0xf3, 0x93, 0xa2, 0xea, 0x27, 0x11, 0xf9,
	0x94, 0x93, 0x25, 0x0c, 0xad, 0x38, 0x00, 0x12, 0x2a, 0x09, 0x44, 0x22, 0x12, 0xac, 0x8d, 0x10,
	0x27, 0x64, 0xec, 0x01, 0xac, 0x26, 0xb6, 0xd9, 0xdd, 0x04, 0xe5, 0x01, 0xb8, 0xf3, 0x76, 0x3c,
	0x04, 0x0f, 0xc0, 0x15, 0xed, 0x6e, 0x42, 0xfe, 0xf9, 0x90, 0x56, 0xdc, 0x3c, 0xb3, 0xdf, 0x37,
	0xfb, 0x7d, 0x33, 0x3b, 0x86, 0xb6, 0xc8, 0xa6, 0x88, 0x73, 0xcc, 0x85, 0x5f, 0xb2, 0x42, 0x14,
	0xde, 0x25, 0x58, 0x03, 0xc6, 0x0a, 0x46, 0x08, 0x1c, 0x5d, 0x17, 0x29, 0x76, 0x8d, 0x9e, 0xd1,
	0xb7, 0xa8, 0xfa, 0x26, 0x5d, 0x38, 0x1e, 0x23, 0xe7, 0xf1, 0x67, 0xec, 0x9a, 0x3d, 0xa3, 0x6f,
	0xd3, 0x55, 0xe8, 0xfd, 0x36, 0x80, 0x8c, 0xa3, 0x6c, 0x8a, 0xa1, 0x88, 0xa7, 0xe5, 0x28, 0x17,
	0xc8, 0xe6, 0xf1, 0x84, 0xbc, 0x84, 0xa6, 0x4c, 0x7e, 0x62, 0xf1, 0x14, 0xc5, 0xa2, 0xd4, 0xd5,
	0x5a, 0x81, 0xe7, 0xef, 0x63, 0x75, 0x6a, 0x28, 0x91, 0xd1, 0xa2, 0x44, 0xba, 0x4d, 0x24, 0xff,
	0x83, 0x1d, 0x8a, 0x98, 0x09, 0x99, 0x55, 0x97, 0xd7, 0xe9, 0x3a, 0x21, 0x85, 0x0d, 0xf2, 0x54,
	0x9d, 0xd5, 0xd5, 0xd9, 0x2a, 0xf4, 0x3e, 0x40, 0x6b, 0xbb, 0x30, 0x69, 0x82, 0x1d, 0x0d, 0xdf,
	0xe6, 0x37, 0x79, 0xf1, 0x2d, 0x77, 0x6b, 0x04, 0xa0, 0x11, 0x0d, 0xdf, 0x21, 0xde, 0xb8, 0x06,
	0x71, 0xe0, 0x38, 0x1a, 0x8e, 0x8b, 0x5c, 0x7c, 0x71, 0x4d, 0x8d, 0x7b, 0x33, 0x8b, 0x99, 0x40,
	0xe6, 0xd6, 0x35, 0xee, 0x3d, 0xc6, 0xcc, 0x3d, 0xd2, 0xdf, 0x61, 0x19, 0xe7, 0xae, 0xe5, 0x7d,
	0x37, 0xc0, 0x95, 0x17, 0x0c, 0x64, 0x13, 0x29, 0x7e, 0x9d, 0x21, 0x17, 0xa4, 0x03, 0x56, 0x54,
	0x94, 0x59, 0xa2, 0xfc, 0xda, 0x54, 0x07, 0x4a, 0xa5, 0x44, 0x8d, 0x52, 0xe5, 0xc0, 0xa2, 0xab,
	0x90, 0x3c, 0x83, 0x33, 0x59, 0x83, 0xcb, 0x86, 0x64, 0xcb, 0x86, 0x28, 0x27, 0x4e, 0x70, 0x5e,
	0xd1, 0x2b, 0xba, 0x8f, 0xf6, 0xee, 0xeb, 0x12, 0x4b, 0x19, 0xbc, 0x2c, 0x72, 0x2e, 0xbb, 0x66,
	0xa1, 0x9c, 0xa6, 0xd2, 0xe1, 0x04, 0x0d, 0x5f, 0xcd, 0x96, 0xea, 0xa4, 0xf7, 0xcb, 0x80, 0xf3,
	0x17, 0x28, 0x0e, 0x54, 0xff, 0x04, 0x6c, 0x85, 0x92, 0x4d, 0x54, 0xfa, 0x5b, 0xc1, 0x3d, 0xbf,
	0x82, 0xee, 0x8f, 0xff, 0xc2, 0xe8, 0x9a, 0xf1, 0x2f, 0x2c, 0x3e, 0x06, 0x58, 0xd7, 0x26, 0x6d,
	0x70, 0x06, 0xd1, 0x28, 0x7f, 0xcd, 0x8a, 0x04, 0x39, 0x77, 0x6b, 0xe4, 0x14, 0x4e, 0x06, 0xd1,
	0x30, 0xce, 0x26, 0x98, 0xba, 0x86, 0x3e, 0x0e, 0x67, 0x49, 0x82, 0x98, 0x62, 0xea, 0x9a, 0xde,
	0x0f, 0x03, 0x9c, 0x70, 0xc1, 0x05, 0x4e, 0x55, 0x0d, 0xd2, 0x02, 0x73, 0x94, 0x2a, 0x8b, 0x4d,
	0x6a, 0x8e, 0xd2, 0xb5, 0x6b, 0x73, 0x67, 0x66, 0xaa, 0x08, 0xe7, 0x4a, 0xec, 0x09, 0x5d, 0x85,
	0xd5, 0x86, 0x8e, 0x6e, 0x65, 0x68, 0x02, 0x9d, 0xed, 0x06, 0x2e, 0xc7, 0x76, 0x05, 0xed, 0x0d,
	0xa5, 0xaf, 0x32, 0x2e, 0xba, 0x46, 0xaf, 0xde, 0x77, 0x82, 0x53, 0x7f, 0x23, 0x4f, 0x77, 0x41,
	0xeb, 0x71, 0x9b, 0x15, 0xe3, 0x0e, 0x7e, 0xd6, 0x37, 0x5e, 0x6a, 0x88, 0x6c, 0x9e, 0x25, 0x48,
	0x1e, 0x82, 0x7d, 0xcd, 0x30, 0x16, 0xf8, 0x3c, 0x5e, 0x90, 0x33, 0x7f, 0x77, 0x98, 0x17, 0xc4,
	0xdf, 0x93, 0xe7, 0xd5, 0xc8, 0x25, 0x80, 0x66, 0xc9, 0xc5, 0x39, 0x9c, 0x76, 0x05, 0x8e, 0xa6,
	0xa9, 0x1d, 0x3b, 0x9c, 0xf7, 0x08, 0x9a, 0x9a, 0xb7, 0x5c, 0xc7, 0x3b, 0x08, 0x95, 0x9b, 0x7b,
	0x07, 0x9a, 0x5c, 0xf2, 0x5b, 0xf9, 0xa3, 0x98, 0x14, 0x2c, 0xd5, 0x2f, 0xec, 0x60, 0xde, 0x53,
	0x68, 0x6e, 0xbe, 0x03, 0x4e, 0x3a, 0x55, 0x8b, 0x75, 0xf1, 0x9f, 0x5f, 0xf5, 0x5a, 0xbc, 0xda,
	0xc7, 0x86, 0xfa, 0x77, 0x3f, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x5d, 0x5c, 0x3c, 0xce,
	0x05, 0x00, 0x00,
}
