// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: timeevent.proto

package timeevent

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MTimeStampInterval_MTimeFrameType int32

const (
	MTimeStampInterval_TFUnknown MTimeStampInterval_MTimeFrameType = 0
	MTimeStampInterval_TFWeek    MTimeStampInterval_MTimeFrameType = 1
	MTimeStampInterval_TFMonth   MTimeStampInterval_MTimeFrameType = 2
	MTimeStampInterval_TFQuarter MTimeStampInterval_MTimeFrameType = 3
	MTimeStampInterval_TFYear    MTimeStampInterval_MTimeFrameType = 4
	MTimeStampInterval_TFSpan    MTimeStampInterval_MTimeFrameType = 5
)

// Enum value maps for MTimeStampInterval_MTimeFrameType.
var (
	MTimeStampInterval_MTimeFrameType_name = map[int32]string{
		0: "TFUnknown",
		1: "TFWeek",
		2: "TFMonth",
		3: "TFQuarter",
		4: "TFYear",
		5: "TFSpan",
	}
	MTimeStampInterval_MTimeFrameType_value = map[string]int32{
		"TFUnknown": 0,
		"TFWeek":    1,
		"TFMonth":   2,
		"TFQuarter": 3,
		"TFYear":    4,
		"TFSpan":    5,
	}
)

func (x MTimeStampInterval_MTimeFrameType) Enum() *MTimeStampInterval_MTimeFrameType {
	p := new(MTimeStampInterval_MTimeFrameType)
	*p = x
	return p
}

func (x MTimeStampInterval_MTimeFrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MTimeStampInterval_MTimeFrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_timeevent_proto_enumTypes[0].Descriptor()
}

func (MTimeStampInterval_MTimeFrameType) Type() protoreflect.EnumType {
	return &file_timeevent_proto_enumTypes[0]
}

func (x MTimeStampInterval_MTimeFrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MTimeStampInterval_MTimeFrameType.Descriptor instead.
func (MTimeStampInterval_MTimeFrameType) EnumDescriptor() ([]byte, []int) {
	return file_timeevent_proto_rawDescGZIP(), []int{1, 0}
}

type GetTimeEventRequest_MEventType int32

const (
	GetTimeEventRequest_ETInProcess GetTimeEventRequest_MEventType = 0
	GetTimeEventRequest_ETFailed    GetTimeEventRequest_MEventType = 1
	GetTimeEventRequest_ETSucceeded GetTimeEventRequest_MEventType = 2
)

// Enum value maps for GetTimeEventRequest_MEventType.
var (
	GetTimeEventRequest_MEventType_name = map[int32]string{
		0: "ETInProcess",
		1: "ETFailed",
		2: "ETSucceeded",
	}
	GetTimeEventRequest_MEventType_value = map[string]int32{
		"ETInProcess": 0,
		"ETFailed":    1,
		"ETSucceeded": 2,
	}
)

func (x GetTimeEventRequest_MEventType) Enum() *GetTimeEventRequest_MEventType {
	p := new(GetTimeEventRequest_MEventType)
	*p = x
	return p
}

func (x GetTimeEventRequest_MEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetTimeEventRequest_MEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_timeevent_proto_enumTypes[1].Descriptor()
}

func (GetTimeEventRequest_MEventType) Type() protoreflect.EnumType {
	return &file_timeevent_proto_enumTypes[1]
}

func (x GetTimeEventRequest_MEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetTimeEventRequest_MEventType.Descriptor instead.
func (GetTimeEventRequest_MEventType) EnumDescriptor() ([]byte, []int) {
	return file_timeevent_proto_rawDescGZIP(), []int{4, 0}
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeevent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_timeevent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_timeevent_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MTimeStampInterval struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timeframetype MTimeStampInterval_MTimeFrameType `protobuf:"varint,1,opt,name=Timeframetype,proto3,enum=MTimeStampInterval_MTimeFrameType" json:"Timeframetype,omitempty"`
	StartTime     int64                             `protobuf:"varint,2,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime       int64                             `protobuf:"varint,3,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
}

func (x *MTimeStampInterval) Reset() {
	*x = MTimeStampInterval{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeevent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MTimeStampInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MTimeStampInterval) ProtoMessage() {}

func (x *MTimeStampInterval) ProtoReflect() protoreflect.Message {
	mi := &file_timeevent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MTimeStampInterval.ProtoReflect.Descriptor instead.
func (*MTimeStampInterval) Descriptor() ([]byte, []int) {
	return file_timeevent_proto_rawDescGZIP(), []int{1}
}

func (x *MTimeStampInterval) GetTimeframetype() MTimeStampInterval_MTimeFrameType {
	if x != nil {
		return x.Timeframetype
	}
	return MTimeStampInterval_TFUnknown
}

func (x *MTimeStampInterval) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *MTimeStampInterval) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type TimeEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic             string              `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	EventId           int32               `protobuf:"varint,2,opt,name=EventId,proto3" json:"EventId,omitempty"`
	Timestampinterval *MTimeStampInterval `protobuf:"bytes,3,opt,name=Timestampinterval,proto3" json:"Timestampinterval,omitempty"`
}

func (x *TimeEventRequest) Reset() {
	*x = TimeEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeevent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeEventRequest) ProtoMessage() {}

func (x *TimeEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timeevent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeEventRequest.ProtoReflect.Descriptor instead.
func (*TimeEventRequest) Descriptor() ([]byte, []int) {
	return file_timeevent_proto_rawDescGZIP(), []int{2}
}

func (x *TimeEventRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TimeEventRequest) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *TimeEventRequest) GetTimestampinterval() *MTimeStampInterval {
	if x != nil {
		return x.Timestampinterval
	}
	return nil
}

type TimeEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *TimeEventResponse) Reset() {
	*x = TimeEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeevent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeEventResponse) ProtoMessage() {}

func (x *TimeEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timeevent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeEventResponse.ProtoReflect.Descriptor instead.
func (*TimeEventResponse) Descriptor() ([]byte, []int) {
	return file_timeevent_proto_rawDescGZIP(), []int{3}
}

func (x *TimeEventResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetTimeEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic             string                         `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	EventType         GetTimeEventRequest_MEventType `protobuf:"varint,2,opt,name=EventType,proto3,enum=GetTimeEventRequest_MEventType" json:"EventType,omitempty"`
	Timestampinterval *MTimeStampInterval            `protobuf:"bytes,3,opt,name=Timestampinterval,proto3" json:"Timestampinterval,omitempty"`
}

func (x *GetTimeEventRequest) Reset() {
	*x = GetTimeEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeevent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimeEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeEventRequest) ProtoMessage() {}

func (x *GetTimeEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timeevent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeEventRequest.ProtoReflect.Descriptor instead.
func (*GetTimeEventRequest) Descriptor() ([]byte, []int) {
	return file_timeevent_proto_rawDescGZIP(), []int{4}
}

func (x *GetTimeEventRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetTimeEventRequest) GetEventType() GetTimeEventRequest_MEventType {
	if x != nil {
		return x.EventType
	}
	return GetTimeEventRequest_ETInProcess
}

func (x *GetTimeEventRequest) GetTimestampinterval() *MTimeStampInterval {
	if x != nil {
		return x.Timestampinterval
	}
	return nil
}

type SystemEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                uint32              `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Topic             string              `protobuf:"bytes,2,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Success           bool                `protobuf:"varint,3,opt,name=Success,proto3" json:"Success,omitempty"`
	Timestampinterval *MTimeStampInterval `protobuf:"bytes,4,opt,name=Timestampinterval,proto3" json:"Timestampinterval,omitempty"`
}

func (x *SystemEvent) Reset() {
	*x = SystemEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeevent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemEvent) ProtoMessage() {}

func (x *SystemEvent) ProtoReflect() protoreflect.Message {
	mi := &file_timeevent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemEvent.ProtoReflect.Descriptor instead.
func (*SystemEvent) Descriptor() ([]byte, []int) {
	return file_timeevent_proto_rawDescGZIP(), []int{5}
}

func (x *SystemEvent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SystemEvent) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SystemEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SystemEvent) GetTimestampinterval() *MTimeStampInterval {
	if x != nil {
		return x.Timestampinterval
	}
	return nil
}

type GetTimeEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SystemEventList []*SystemEvent `protobuf:"bytes,1,rep,name=SystemEventList,proto3" json:"SystemEventList,omitempty"`
	Error           *Error         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetTimeEventResponse) Reset() {
	*x = GetTimeEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeevent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimeEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeEventResponse) ProtoMessage() {}

func (x *GetTimeEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timeevent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeEventResponse.ProtoReflect.Descriptor instead.
func (*GetTimeEventResponse) Descriptor() ([]byte, []int) {
	return file_timeevent_proto_rawDescGZIP(), []int{6}
}

func (x *GetTimeEventResponse) GetSystemEventList() []*SystemEvent {
	if x != nil {
		return x.SystemEventList
	}
	return nil
}

func (x *GetTimeEventResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_timeevent_proto protoreflect.FileDescriptor

var file_timeevent_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x35, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xf7, 0x01, 0x0a, 0x12, 0x4d, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12,
	0x48, 0x0a, 0x0d, 0x54, 0x69, 0x6d, 0x65, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x4d, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x6d, 0x70, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x2e, 0x4d, 0x54, 0x69, 0x6d,
	0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0d, 0x54, 0x69, 0x6d, 0x65,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x5f, 0x0a, 0x0e, 0x4d, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x46, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x46, 0x57, 0x65, 0x65, 0x6b, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x54, 0x46, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x54,
	0x46, 0x51, 0x75, 0x61, 0x72, 0x74, 0x65, 0x72, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x46,
	0x59, 0x65, 0x61, 0x72, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x46, 0x53, 0x70, 0x61, 0x6e,
	0x10, 0x05, 0x22, 0x85, 0x01, 0x0a, 0x10, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x18, 0x0a,
	0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x41, 0x0a, 0x11, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4d, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x52, 0x11, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x31, 0x0a, 0x11, 0x54, 0x69,
	0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xeb, 0x01,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x3d, 0x0a, 0x09, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x41, 0x0a, 0x11, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4d, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x6d, 0x70, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x52, 0x11, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x3c, 0x0a,
	0x0a, 0x4d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x45,
	0x54, 0x49, 0x6e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x45, 0x54, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x54,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x10, 0x02, 0x22, 0x90, 0x01, 0x0a, 0x0b,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x41, 0x0a, 0x11, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4d, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x6d, 0x70, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x52, 0x11, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x6c,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0f, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0f, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xd7, 0x03, 0x0a,
	0x10, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x34, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x61, 0x79, 0x12, 0x11,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x57, 0x65, 0x65, 0x6b, 0x12, 0x11, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x36,
	0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x11, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x51, 0x75, 0x61, 0x72, 0x74, 0x65, 0x72, 0x12, 0x11, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x35, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x59, 0x65, 0x61, 0x72, 0x12, 0x11,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x70, 0x61, 0x6e, 0x12, 0x11, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x36,
	0x0a, 0x0b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x11, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_timeevent_proto_rawDescOnce sync.Once
	file_timeevent_proto_rawDescData = file_timeevent_proto_rawDesc
)

func file_timeevent_proto_rawDescGZIP() []byte {
	file_timeevent_proto_rawDescOnce.Do(func() {
		file_timeevent_proto_rawDescData = protoimpl.X.CompressGZIP(file_timeevent_proto_rawDescData)
	})
	return file_timeevent_proto_rawDescData
}

var file_timeevent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_timeevent_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_timeevent_proto_goTypes = []interface{}{
	(MTimeStampInterval_MTimeFrameType)(0), // 0: MTimeStampInterval.MTimeFrameType
	(GetTimeEventRequest_MEventType)(0),    // 1: GetTimeEventRequest.MEventType
	(*Error)(nil),                          // 2: Error
	(*MTimeStampInterval)(nil),             // 3: MTimeStampInterval
	(*TimeEventRequest)(nil),               // 4: TimeEventRequest
	(*TimeEventResponse)(nil),              // 5: TimeEventResponse
	(*GetTimeEventRequest)(nil),            // 6: GetTimeEventRequest
	(*SystemEvent)(nil),                    // 7: SystemEvent
	(*GetTimeEventResponse)(nil),           // 8: GetTimeEventResponse
}
var file_timeevent_proto_depIdxs = []int32{
	0,  // 0: MTimeStampInterval.Timeframetype:type_name -> MTimeStampInterval.MTimeFrameType
	3,  // 1: TimeEventRequest.Timestampinterval:type_name -> MTimeStampInterval
	2,  // 2: TimeEventResponse.error:type_name -> Error
	1,  // 3: GetTimeEventRequest.EventType:type_name -> GetTimeEventRequest.MEventType
	3,  // 4: GetTimeEventRequest.Timestampinterval:type_name -> MTimeStampInterval
	3,  // 5: SystemEvent.Timestampinterval:type_name -> MTimeStampInterval
	7,  // 6: GetTimeEventResponse.SystemEventList:type_name -> SystemEvent
	2,  // 7: GetTimeEventResponse.error:type_name -> Error
	4,  // 8: TimeEventService.CreateDay:input_type -> TimeEventRequest
	4,  // 9: TimeEventService.CreateWeek:input_type -> TimeEventRequest
	4,  // 10: TimeEventService.CreateMonth:input_type -> TimeEventRequest
	4,  // 11: TimeEventService.CreateQuarter:input_type -> TimeEventRequest
	4,  // 12: TimeEventService.CreateYear:input_type -> TimeEventRequest
	4,  // 13: TimeEventService.CreateSpan:input_type -> TimeEventRequest
	4,  // 14: TimeEventService.RecordEvent:input_type -> TimeEventRequest
	6,  // 15: TimeEventService.GetTimeEvents:input_type -> GetTimeEventRequest
	5,  // 16: TimeEventService.CreateDay:output_type -> TimeEventResponse
	5,  // 17: TimeEventService.CreateWeek:output_type -> TimeEventResponse
	5,  // 18: TimeEventService.CreateMonth:output_type -> TimeEventResponse
	5,  // 19: TimeEventService.CreateQuarter:output_type -> TimeEventResponse
	5,  // 20: TimeEventService.CreateYear:output_type -> TimeEventResponse
	5,  // 21: TimeEventService.CreateSpan:output_type -> TimeEventResponse
	5,  // 22: TimeEventService.RecordEvent:output_type -> TimeEventResponse
	8,  // 23: TimeEventService.GetTimeEvents:output_type -> GetTimeEventResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_timeevent_proto_init() }
func file_timeevent_proto_init() {
	if File_timeevent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_timeevent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeevent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MTimeStampInterval); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeevent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeevent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeevent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTimeEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeevent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeevent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTimeEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_timeevent_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_timeevent_proto_goTypes,
		DependencyIndexes: file_timeevent_proto_depIdxs,
		EnumInfos:         file_timeevent_proto_enumTypes,
		MessageInfos:      file_timeevent_proto_msgTypes,
	}.Build()
	File_timeevent_proto = out.File
	file_timeevent_proto_rawDesc = nil
	file_timeevent_proto_goTypes = nil
	file_timeevent_proto_depIdxs = nil
}
